version: '3.9'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    tty: true
    restart: unless-stopped

  api:
    build:
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./piper/models:/piper/models
      - ./data:/app/data
    environment:
      - OUTPUT_DIR=/app/data/output
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama-models:
